### PR TITLE
feature/extras-menu

### PR DESCRIPTION
**Pull request by TwilightKillerX**
Added an Extras Menu:
- Collect Gage Packages on the map
- Board all windows
- Open all deposit boxes (Banks)
- Tie civilians
- Show/Hide invisible walls on the map (visual only)
- Lock up / Release AI from custody
- Enable / Disable cash penalty for civilians

### CODE REVIEW

**Comment by pierre-josselin** [comment]
Very nice, these features were expected by many people.
Thanks for sharing

**Comment by pierre-josselin** [comment]
Could you please use the english locale file for the alerts?

**Comment by TwilightKillerX** [comment]
> Could you please use the english locale file for the alerts?

Added in the [latest commit ](https://github.com/pierre-josselin/payday-2-ultimate-trainer-5/pull/82/commits/8ed0dc953153c5ac248479da7a01b3732d31f08a) 👍

**Comment by pierre-josselin** [comment]
> Could you please use the english locale file for the alerts?

Thank you!

**Pull request merged**
